import { Shop, Product, KhataCustomer, Order, SubscriptionRequest } from '../types';

export const DEMO_SHOP_OWNER_1 = 'owner_kgn_main';
export const DEMO_SHOP_OWNER_2 = 'owner_al_madina';
export const DEMO_SHOP_OWNER_3 = 'owner_bismillah_free';

export const INITIAL_SHOPS: Shop[] = [
  {
    id: 'shop_kgn_01',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopName: 'KGN Super Market & Kirana',
    slug: 'kgn-supermarket',
    tagline: 'Fresh Groceries, Spices, Daily Kirana & Household Essentials',
    category: 'Grocery & Kirana',
    phone: '+91 98765 43210',
    whatsappNumber: '919876543210',
    upiId: 'seikhsarif16@oksbi',
    address: 'Shop No. 12, Main Bazar, Near Jama Masjid',
    city: 'Mumbai',
    pincode: '400008',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=1200&auto=format&fit=crop&q=80',
    tier: 'pro',
    currency: '₹',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'shop_al_madina_02',
    shopOwnerId: DEMO_SHOP_OWNER_2,
    shopName: 'Al-Madina Electronics & Mobile Hub',
    slug: 'al-madina-electronics',
    tagline: 'Smartphones, Smartwatches, Mobile Accessories & Repair',
    category: 'Electronics & Mobiles',
    phone: '+91 91234 56789',
    whatsappNumber: '919123456789',
    upiId: 'almadina@icici',
    address: 'G-04, City Plaza Commercial Complex',
    city: 'Hyderabad',
    pincode: '500002',
    logoUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=1200&auto=format&fit=crop&q=80',
    tier: 'starter',
    currency: '₹',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'shop_bismillah_03',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopName: 'Bismillah Corner Store (Free Plan Demo)',
    slug: 'bismillah-corner-store',
    tagline: 'Neighborhood daily essentials & cold beverages (Free Plan 14/15 Products)',
    category: 'Grocery & Kirana',
    phone: '+91 98333 11223',
    whatsappNumber: '919833311223',
    upiId: 'bismillahstore@paytm',
    address: 'Corner Shop, Golibar Road, Santacruz East',
    city: 'Mumbai',
    pincode: '400055',
    logoUrl: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1588964895597-cfccd6e2dbf9?w=1200&auto=format&fit=crop&q=80',
    tier: 'free',
    currency: '₹',
    isActive: true,
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  // Shop 1 Products (KGN Super Market)
  {
    id: 'prod_kgn_01',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopId: 'shop_kgn_01',
    name: 'Fortune Sunlite Refined Sunflower Oil (1L)',
    description: 'Enriched with Vitamin A & D for healthy cooking.',
    category: 'Oils & Ghee',
    mrp: 180,
    sellingPrice: 155,
    stockQuantity: 45,
    unit: 'liter',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80',
    barcode: '8901234001',
    isFeatured: true,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_kgn_02',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopId: 'shop_kgn_01',
    name: 'India Gate Basmati Rice Premium Dubar (5kg)',
    description: 'Long grain aromatic basmati rice for biryani & daily meals.',
    category: 'Rice & Grains',
    mrp: 550,
    sellingPrice: 480,
    stockQuantity: 28,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80',
    barcode: '8901234002',
    isFeatured: true,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_kgn_03',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopId: 'shop_kgn_01',
    name: 'Tata Tea Gold Leaf Premium Blend (500g)',
    description: 'Gently rolled aromatic long leaves with rich CTC aroma.',
    category: 'Beverages & Tea',
    mrp: 320,
    sellingPrice: 285,
    stockQuantity: 34,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=500&auto=format&fit=crop&q=80',
    barcode: '8901234003',
    isFeatured: true,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_kgn_04',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopId: 'shop_kgn_01',
    name: 'Aashirvaad Shudh Chakki Atta (10kg)',
    description: '100% Whole Wheat flour with dietary fiber.',
    category: 'Flour & Atta',
    mrp: 440,
    sellingPrice: 410,
    stockQuantity: 19,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80',
    barcode: '8901234004',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_kgn_05',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopId: 'shop_kgn_01',
    name: 'Everest Royal Garam Masala (100g)',
    description: 'Special authentic aromatic spice mix.',
    category: 'Spices & Masalas',
    mrp: 95,
    sellingPrice: 85,
    stockQuantity: 50,
    unit: 'box',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80',
    barcode: '8901234005',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_kgn_06',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopId: 'shop_kgn_01',
    name: 'Almonds Premium California Badam (250g)',
    description: 'Crunchy, fresh, high-grade nutrient-rich almonds.',
    category: 'Dry Fruits & Nuts',
    mrp: 300,
    sellingPrice: 240,
    stockQuantity: 12,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=500&auto=format&fit=crop&q=80',
    barcode: '8901234006',
    isFeatured: true,
    status: 'low_stock',
    createdAt: new Date().toISOString(),
  },

  // Shop 2 Products (Al-Madina Electronics)
  {
    id: 'prod_med_01',
    shopOwnerId: DEMO_SHOP_OWNER_2,
    shopId: 'shop_al_madina_02',
    name: 'Boat Bassheads 242 Wired In-Ear Earphones',
    description: 'HD Sound with 10mm dynamic drivers and IPX4 sweat resistance.',
    category: 'Audio & Earphones',
    mrp: 999,
    sellingPrice: 499,
    stockQuantity: 15,
    unit: 'piece',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80',
    barcode: '8909876001',
    isFeatured: true,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_med_02',
    shopOwnerId: DEMO_SHOP_OWNER_2,
    shopId: 'shop_al_madina_02',
    name: 'Mi 20000mAh Power Bank 3i Fast Charging',
    description: '18W Fast Charging with Triple Output and Dual Input ports.',
    category: 'Power & Cables',
    mrp: 2199,
    sellingPrice: 1799,
    stockQuantity: 8,
    unit: 'piece',
    imageUrl: 'https://images.unsplash.com/photo-1609592424364-54124939b431?w=500&auto=format&fit=crop&q=80',
    barcode: '8909876002',
    isFeatured: true,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },

  // Shop 3 Products (Bismillah Corner Store - Free Tier Demo 14/15 items)
  {
    id: 'prod_bis_01',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Amul Taaza Homogenised Toned Milk (1L)',
    description: 'Pasteurised toned milk with 3.0% fat.',
    category: 'Dairy & Milk',
    mrp: 72,
    sellingPrice: 70,
    stockQuantity: 30,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235001',
    isFeatured: true,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_02',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Britannia Good Day Butter Cookies (200g)',
    description: 'Rich butter cookies with smiles.',
    category: 'Snacks & Biscuits',
    mrp: 40,
    sellingPrice: 35,
    stockQuantity: 50,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235002',
    isFeatured: true,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_03',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Maggi 2-Minute Instant Noodles (4-Pack)',
    description: 'Classic Masala tastemaker instant noodles.',
    category: 'Instant Food',
    mrp: 60,
    sellingPrice: 55,
    stockQuantity: 40,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235003',
    isFeatured: true,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_04',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Coca-Cola Zero Sugar Can (330ml)',
    description: 'Refreshing sparkling zero calorie soft drink.',
    category: 'Beverages',
    mrp: 40,
    sellingPrice: 38,
    stockQuantity: 24,
    unit: 'can',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235004',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_05',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Parle-G Gold Glucose Biscuits (1kg)',
    description: 'India\'s favorite tea companion biscuits.',
    category: 'Snacks & Biscuits',
    mrp: 120,
    sellingPrice: 110,
    stockQuantity: 18,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235005',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_06',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Lipton Yellow Label Pure Green Tea (25 Bags)',
    description: 'Rich in antioxidants, invigorating fresh taste.',
    category: 'Tea & Coffee',
    mrp: 175,
    sellingPrice: 160,
    stockQuantity: 12,
    unit: 'box',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235006',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_07',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Dettol Original Germ Protection Soap (4x125g)',
    description: 'Be 100% sure of germ protection.',
    category: 'Personal Care',
    mrp: 210,
    sellingPrice: 195,
    stockQuantity: 15,
    unit: 'pack',
    imageUrl: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235007',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_08',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Colgate MaxFresh Peppermint Toothpaste (150g)',
    description: 'Cooling crystals for intense freshness.',
    category: 'Personal Care',
    mrp: 110,
    sellingPrice: 99,
    stockQuantity: 20,
    unit: 'piece',
    imageUrl: 'https://images.unsplash.com/photo-1559591937-e10321526367?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235008',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_09',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Haldiram\'s Nagpur Bhujia Sev (400g)',
    description: 'Spicy crispy moth bean & besan snack.',
    category: 'Snacks & Biscuits',
    mrp: 140,
    sellingPrice: 130,
    stockQuantity: 22,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235009',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_10',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Aashirvaad Shudh Chakki Atta (5kg)',
    description: '100% whole wheat flour, rotis stay soft longer.',
    category: 'Flours & Grains',
    mrp: 260,
    sellingPrice: 245,
    stockQuantity: 14,
    unit: 'bag',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235010',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_11',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Tata Salt Vaccum Evaporated (1kg)',
    description: 'Desh Ka Namak with guaranteed iodine.',
    category: 'Spices & Seasoning',
    mrp: 28,
    sellingPrice: 25,
    stockQuantity: 60,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235011',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_12',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Catch Super Garam Masala Powder (100g)',
    description: 'Aromatic traditional Indian spice blend.',
    category: 'Spices & Seasoning',
    mrp: 85,
    sellingPrice: 79,
    stockQuantity: 16,
    unit: 'box',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235012',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_13',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Surf Excel Easy Wash Detergent Powder (1kg)',
    description: 'Removes tough stains easily like oil, gravy & clay.',
    category: 'Household & Cleaning',
    mrp: 145,
    sellingPrice: 135,
    stockQuantity: 15,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1585842378054-ee2e52f94ba2?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235013',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_bis_14',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopId: 'shop_bismillah_03',
    name: 'Vim Dishwash Gel Lemon (500ml Bottle)',
    description: 'Power of 100 lemons with easy grease removal.',
    category: 'Household & Cleaning',
    mrp: 125,
    sellingPrice: 115,
    stockQuantity: 20,
    unit: 'bottle',
    imageUrl: 'https://images.unsplash.com/photo-1585842378081-5c74a20b318c?w=500&auto=format&fit=crop&q=80',
    barcode: '8901235014',
    isFeatured: false,
    status: 'in_stock',
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_KHATA_CUSTOMERS: KhataCustomer[] = [
  {
    id: 'khata_cust_01',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopId: 'shop_kgn_01',
    name: 'Mohammad Rashid Khan',
    phone: '+91 98201 11223',
    address: 'Flat 302, Noor Manzil, Main Road',
    currentBalance: 1850, // owes ₹1850
    creditLimit: 5000,
    lastTransactionDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'khata_cust_02',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopId: 'shop_kgn_01',
    name: 'Imran Bhai Contractor',
    phone: '+91 98202 44556',
    address: 'B-Wing 104, Gulshan Heights',
    currentBalance: 3420, // owes ₹3420
    creditLimit: 10000,
    lastTransactionDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'khata_cust_03',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopId: 'shop_kgn_01',
    name: 'Suresh Patel (Tailor)',
    phone: '+91 98203 77889',
    address: 'Opposite Railway Station Bazar',
    currentBalance: -500, // advance ₹500
    creditLimit: 3000,
    lastTransactionDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_kgn_101',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopId: 'shop_kgn_01',
    orderNumber: 'KGN-ORD-1001',
    customerName: 'Amina Khatoon',
    customerPhone: '+91 97654 32109',
    deliveryAddress: 'House #45, Near Old Water Tank, Mumbai',
    deliveryType: 'delivery',
    items: [
      {
        productId: 'prod_kgn_01',
        name: 'Fortune Sunlite Refined Sunflower Oil (1L)',
        price: 155,
        quantity: 2,
        unit: 'liter',
        imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80',
        total: 310
      },
      {
        productId: 'prod_kgn_03',
        name: 'Tata Tea Gold Leaf Premium Blend (500g)',
        price: 285,
        quantity: 1,
        unit: 'packet',
        imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=500&auto=format&fit=crop&q=80',
        total: 285
      }
    ],
    subtotal: 595,
    discount: 25,
    totalAmount: 570,
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    orderStatus: 'accepted',
    notes: 'Please ring bell twice upon arrival',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  }
];

export const INITIAL_SUBSCRIPTION_REQUESTS: SubscriptionRequest[] = [
  {
    id: 'req_sub_201',
    shopId: 'shop_bismillah_03',
    shopOwnerId: DEMO_SHOP_OWNER_3,
    shopName: 'Bismillah Corner Store',
    ownerEmail: 'bismillah@demo.com',
    ownerPhone: '+91 98333 11223',
    requestedTier: 'pro',
    amount: 499,
    billingCycle: 'monthly',
    paymentMethod: 'upi',
    upiId: 'seikhsarif16@oksbi',
    utrNumber: '423981123490',
    status: 'pending',
    submittedAt: new Date(Date.now() - 7200000).toISOString()
  },
  {
    id: 'req_sub_202',
    shopId: 'shop_al_madina_02',
    shopOwnerId: DEMO_SHOP_OWNER_2,
    shopName: 'Al-Madina Electronics & Mobile Hub',
    ownerEmail: 'almadina@demo.com',
    ownerPhone: '+91 91234 56789',
    requestedTier: 'pro',
    amount: 499,
    billingCycle: 'monthly',
    paymentMethod: 'upi',
    upiId: 'seikhsarif16@oksbi',
    utrNumber: '423998765412',
    status: 'pending',
    submittedAt: new Date(Date.now() - 14400000).toISOString()
  },
  {
    id: 'req_sub_203',
    shopId: 'shop_kgn_01',
    shopOwnerId: DEMO_SHOP_OWNER_1,
    shopName: 'KGN Super Market & Kirana',
    ownerEmail: 'kgn.store@demo.com',
    ownerPhone: '+91 98765 43210',
    requestedTier: 'starter',
    amount: 199,
    billingCycle: 'monthly',
    paymentMethod: 'upi',
    upiId: 'seikhsarif16@oksbi',
    utrNumber: '423955667788',
    status: 'approved',
    submittedAt: new Date(Date.now() - 86400000).toISOString(),
    reviewedAt: new Date(Date.now() - 43200000).toISOString(),
    reviewedBy: 'seikhsarif16@gmail.com'
  }
];

